"use client";
import { FormEvent, useState } from "react";
import { CONTACT } from "@/data/site";
import { Icon } from "./Icon";
type Status = "idle" | "submitting" | "success" | "error";
const TEAM_SIZES = ["1 - 14", "15 - 49", "50 - 199", "200+"];
export default function LeadForm() {
  const [status, setStatus] = useState<Status>("idle"); const [errorMessage, setErrorMessage] = useState("");
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus("submitting"); setErrorMessage(""); const form=event.currentTarget; const data=new FormData(form); const payload={name:String(data.get("name")||""),email:String(data.get("email")||""),company:String(data.get("company")||""),teamSize:String(data.get("teamSize")||""),message:String(data.get("message")||"")}; try { const res=await fetch("/api/lead",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}); const result=await res.json(); if(!res.ok) throw new Error(result.error||"Something went wrong."); setStatus("success"); form.reset(); } catch(err){setStatus("error");setErrorMessage(err instanceof Error?err.message:"Something went wrong.");} }
  return <section id="lead-form" className="section bg-gradient-to-b from-ink-50 to-white"><div className="container-xl"><div className="grid grid-cols-1 gap-10 rounded-3xl border border-ink-100 bg-white p-6 shadow-soft sm:p-10 lg:grid-cols-2 lg:gap-16 lg:p-14"><div><span className="eyebrow">Get Started</span><h2 className="section-heading mt-4">Talk to an Enterprise Learning Specialist</h2><p className="section-sub">Tell us about your team and we&apos;ll get back to you with a customized skill framework, cohort pricing, and a detailed syllabus.</p><div className="mt-8 space-y-4"><a href={`tel:${CONTACT.phone.replace(/\s+/g,"")}`} className="flex items-center gap-3 text-sm font-semibold text-ink-800 hover:text-brand-700"><Icon name="phone" className="h-4 w-4" />{CONTACT.phone}</a><a href={`mailto:${CONTACT.email}`} className="flex items-center gap-3 text-sm font-semibold text-ink-800 hover:text-brand-700"><Icon name="mail" className="h-4 w-4" />{CONTACT.email}</a></div></div><div>{status==="success"?<div className="flex h-full flex-col items-center justify-center rounded-2xl bg-brand-50 p-10 text-center"><Icon name="check" className="h-8 w-8 text-brand-600"/><h3 className="mt-4 text-lg font-bold text-ink-900">Request received!</h3><p className="mt-2 text-sm text-ink-600">Thanks for reaching out. An Accredian Enterprise specialist will contact you within one business day.</p></div>:<form onSubmit={handleSubmit} className="space-y-4"><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><input name="name" required placeholder="Full Name" className="w-full rounded-xl border border-ink-100 px-4 py-3 text-sm"/><input name="email" type="email" required placeholder="Work Email" className="w-full rounded-xl border border-ink-100 px-4 py-3 text-sm"/></div><input name="company" required placeholder="Company Name" className="w-full rounded-xl border border-ink-100 px-4 py-3 text-sm"/><select name="teamSize" required defaultValue="" className="w-full rounded-xl border border-ink-100 bg-white px-4 py-3 text-sm"><option value="" disabled>Select team size</option>{TEAM_SIZES.map(size=><option key={size}>{size} employees</option>)}</select><textarea name="message" rows={3} placeholder="What are you looking to achieve?" className="w-full rounded-xl border border-ink-100 px-4 py-3 text-sm"/>{status==="error"&&<p className="text-sm text-red-600">{errorMessage}</p>}<button type="submit" disabled={status==="submitting"} className="btn-primary w-full">{status==="submitting"?"Sending...":"Request Skill Assessment"}</button></form>}</div></div></div></section>;
}
